name: defood
description: An app for managing your food
publish_to: "none"
version: 0.2.0-dev1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.6.0
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_logs: ^2.1.12
  open_filex: ^4.5.0
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  android_system_font:
    git:
      url: https://github.com/re7gog/android_system_font
      ref: master
  flutter_archive: ^6.0.3
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  flutter_markdown: ^0.7.3+1
  device_info_plus: ^10.1.2
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  dart_mappable: ^4.2.2
  flutter_expandable_fab: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  stacked_generator: ^1.6.1
  envied_generator: ^0.5.4+1
  change_app_package_name: ^1.3.0
  dart_mappable_builder: ^4.2.3
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/defood.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/github/github.svg"
    - "assets/images/food.svg"

flutter_native_splash:
  color: "#024270"
  image: assets/icon/glassdown.png
  android_12:
    image: assets/icon/glassdown_a12.png
    color: "#024270"