name: defood
description: An app for managing your food
publish_to: "none"
version: 0.3.0-dev1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_logs: ^2.2.1
  open_filex: ^4.7.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  android_system_font:
    git:
      url: https://github.com/re7gog/android_system_font
      ref: master
  flutter_archive: ^6.0.3
  path_provider: ^2.1.5
  file_picker: ^10.2.0
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  animations: ^2.0.11
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1
  device_info_plus: ^11.5.0
  supabase_flutter: ^2.9.1
  google_sign_in: ^7.1.1
  slang: ^4.7.3
  slang_flutter: ^4.7.0
  dart_mappable: ^4.5.0
  flutter_expandable_fab: ^2.5.2
  material_symbols_icons: ^4.2815.1
  openfoodfacts: ^3.24.0
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  currency_text_input_formatter: ^2.3.0
  pocketbase: ^0.23.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  stacked_generator: ^1.6.1
  envied_generator: ^1.1.1
  change_app_package_name: ^1.5.0
  dart_mappable_builder: ^4.3.1+1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/defood.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/github/github.svg"
    - "assets/images/food.svg"

flutter_native_splash:
  color: "#c5c6f6"
  image: assets/icon/defood.png
  android_12:
    image: assets/icon/defood_a12.png
    branding: assets/icon/banner.png
    color: "#c5c6f6"
