name: defood
description: An app for managing your food
publish_to: 'none'
version: 0.1.0-dev1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.6.0
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_logs: ^2.1.12
  open_filex: ^4.5.0
  package_info_plus: ^8.0.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  android_system_font:
    git:
      url: https://github.com/re7gog/android_system_font
      ref: master
  flutter_archive: ^6.0.3
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  animations: ^2.0.11

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

